apiVersion: v1
kind: Service
metadata:
  name: my-np-service
spec:
  type: NodePort
  selector:
    name: rs-label
    type: back-end
  ports:
  - protocol: TCP
    nodePort: 30010
    port: 8080
    targetPort: 80

